api_rest:
    resource: ../../src/Presentation/Api/Rest/Controller/
    type: annotation
    prefix: /api

front:
    resource: ../../src/Presentation/Front/Controller/
    type: annotation
    prefix: /
